<?php

declare(strict_types=1);

namespace JPI\CRUD\API\Tests;

use JPI\CRUD\API\Tests\Fixtures\TestCrudService;
use JPI\CRUD\API\Tests\Fixtures\TestEntity;
use JPI\Database;
use JPI\HTTP\Request;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\MockObject\Stub;
use PHPUnit\Framework\TestCase;

/**
 * Test SQL queries generated by CrudService index operations
 *
 * Tests verify that filtering, searching, sorting, and pagination
 * produce the correct SQL queries as requested in the issue.
 *
 * @covers \JPI\CRUD\API\CrudService::index
 * @covers \JPI\CRUD\API\Entity\FilterableTrait
 * @covers \JPI\CRUD\API\Entity\SearchableTrait
 * @covers \JPI\CRUD\API\Entity\SortableTrait
 */
final class CrudServiceIndexTest extends TestCase {

    private function createDatabase(): Database&MockObject {
        $database = $this->createMock(Database::class);
        TestEntity::setDatabase($database);
        return $database;
    }

    private function createRequest(array $queryParams = []): Request&Stub {
        $request = $this->createStub(Request::class);

        $queryParams = new \JPI\HTTP\Input($queryParams);

        $request->method("getQueryParam")
            ->willReturnCallback(function ($key) use ($queryParams) {
                return $queryParams[$key] ?? null;
            })
        ;

        $request->method("hasQueryParam")
            ->willReturnCallback(function ($key) use ($queryParams) {
                return isset($queryParams[$key]);
            })
        ;

        return $request;
    }

    public function testLimit(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 3;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $request = $this->createRequest([
            "limit" => 3,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public static function invalidLimitValueProvider(): array {
        return [
            "string value (non-numeric)" => ["not a number"],
            "array value" => [["2"]],
            "negative number" => [-5],
            "zero" => [0],
        ];
    }

    #[DataProvider('invalidLimitValueProvider')]
    public function testInvalidLimitValue(mixed $invalidLimit): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($this->createRequest(["limit" => $invalidLimit]));
    }

    public function testPagination(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10 OFFSET 20;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $request = $this->createRequest([
            "page" => 3,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public static function invalidPaginationValueProvider(): array {
        return [
            "string value (non-numeric)" => ["not a number"],
            "array value" => [["2"]],
            "negative number" => [-2],
            "zero" => [0],
        ];
    }

    #[DataProvider('invalidPaginationValueProvider')]
    public function testInvalidPaginationValue(mixed $invalidPage): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($this->createRequest(["page" => $invalidPage]));
    }

    public function testFiltering(): void {
        $this->createDatabase()->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([
                    "status" => "active",
                    "category" => "test",
                ])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest([
            "filters" => [
                "status" => "active",
                "category" => "test",
                "nonexistent_column" => "foo",
            ],
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public static function invalidFilterValueProvider(): array {
        return [
            "string value instead of array" => ["im a string filter"],
            "nested array values" => [["key" => ["im nested"]]],
        ];
    }

    #[DataProvider('invalidFilterValueProvider')]
    public function testInvalidFilterValue(mixed $invalidFilters): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($this->createRequest(["filters" => $invalidFilters]));
    }

    public function testSearching(): void {
        $this->createDatabase()->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([
                    "search" => "%hello%world%",
                    "searchReversed" => "%world%hello%",
                ])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest([
            "search" => "hello world",
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public static function invalidSearchValueProvider(): array {
        return [
            "array value instead of string" => [["in array"]],
        ];
    }

    #[DataProvider('invalidSearchValueProvider')]
    public function testInvalidSearchValue(mixed $invalidSearch): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($this->createRequest(["search" => $invalidSearch]));
    }

    public function testSorting(): void {
        $this->createDatabase()->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name ASC, created_at DESC, id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest([
            "sort" => "name:asc,nonexistent_column,created_at : DESC,id", // Nonexistent, space and case variations
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public static function invalidSortValueProvider(): array {
        return [
            "array value instead of string" => [["in array"]],
        ];
    }

    #[DataProvider('invalidSortValueProvider')]
    public function testInvalidSortValue(mixed $invalidSort): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($this->createRequest(["sort" => $invalidSort]));
    }

    public function testFiltersWithSearch(): void {
        $this->createDatabase()->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([
                    "status" => "active",
                    "search" => "%test%",
                    "searchReversed" => "%test%",
                ])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest([
            "filters" => [
                "status" => "active",
            ],
            "search" => "test",
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testEverything(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY name DESC, created_at ASC
LIMIT 10 OFFSET 10;"),
                $this->equalTo([
                    "status" => "active",
                    "category" => "test",
                    "search" => "%hello%world%",
                    "searchReversed" => "%world%hello%",
                ])
            )
            ->willReturn([])
        ;

        $database->method("selectFirst")->willReturn(["count" => 20]);

        $request = $this->createRequest([
            "filters" => [
                "status" => "active",
                "category" => "test",
            ],
            "search" => "hello world",
            "sort" => "name:desc,created_at:asc",
            "limit" => 10,
            "page" => 2,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }
}
