<?php

declare(strict_types=1);

namespace JPI\CRUD\API\Tests;

use JPI\CRUD\API\Tests\Fixtures\TestCrudService;
use JPI\CRUD\API\Tests\Fixtures\TestEntity;
use JPI\Database;
use JPI\HTTP\Request;
use JPI\ORM\Entity\QueryBuilder;
use PHPUnit\Framework\TestCase;

/**
 * Test SQL queries generated by CrudService index operations
 *
 * Tests verify that filtering, searching, sorting, and pagination
 * produce the correct SQL queries as requested in the issue.
 */
final class CrudQueryTest extends TestCase {

    private function createMockDatabase(): Database {
        return $this->createMock(Database::class);
    }

    private function createQueryBuilder(?Database $database = null): QueryBuilder {
        $entity = new TestEntity();
        return new QueryBuilder($database ?: $this->createMockDatabase(), $entity);
    }

    private function createMockRequest(array $queryParams = []): Request {
        $request = $this->createMock(Request::class);
        
        $request->method('getQueryParam')
            ->willReturnCallback(function ($key) use ($queryParams) {
                return $queryParams[$key] ?? null;
            });
        
        $request->method('hasQueryParam')
            ->willReturnCallback(function ($key) use ($queryParams) {
                return isset($queryParams[$key]);
            });
        
        return $request;
    }

    public function testFilteringGeneratesCorrectWhereClause(): void {
        $database = $this->createMockDatabase();

        // Expect the selectAll method to be called with specific SQL
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category
ORDER BY id ASC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([
                    'status' => 'active',
                    'category' => 'test',
                ])
            )
            ->willReturn([]);

        // Set database on entity
        TestEntity::setDatabase($database);

        $request = $this->createMockRequest([
            'filters' => [
                'status' => 'active',
                'category' => 'test',
            ],
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSearchingGeneratesCorrectWhereClause(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to be called with specific SQL including OR conditions
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([
                    'search' => '%hello%world%',
                    'searchReversed' => '%world%hello%',
                ])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        $request = $this->createMockRequest([
            'search' => 'hello world',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSortingGeneratesCorrectOrderBy(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to be called with specific ORDER BY
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name ASC, created_at DESC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        $request = $this->createMockRequest([
            'sort' => 'name:asc,created_at:desc',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testMultipleFiltersWithSearch(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to be called with combined WHERE conditions
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([
                    'status' => 'active',
                    'search' => '%test%',
                    'searchReversed' => '%test%',
                ])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        $request = $this->createMockRequest([
            'filters' => [
                'status' => 'active',
            ],
            'search' => 'test',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testComplexQueryWithFilterSearchAndSort(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to be called with all query modifications
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY name DESC, created_at ASC
LIMIT 10 OFFSET 10;"),
                $this->equalTo([
                    'status' => 'active',
                    'category' => 'test',
                    'search' => '%hello%world%',
                    'searchReversed' => '%world%hello%',
                ])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        $request = $this->createMockRequest([
            'filters' => [
                'status' => 'active',
                'category' => 'test',
            ],
            'search' => 'hello world',
            'sort' => 'name:desc,created_at:asc',
            'limit' => 10,
            'page' => 2,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testFilterIgnoresNonFilterableColumns(): void {
        $database = $this->createMockDatabase();

        // Expect only filterable columns in WHERE clause
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status
ORDER BY id ASC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([
                    'status' => 'active',
                ])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        // Try to filter by a non-filterable column
        $request = $this->createMockRequest([
            'filters' => [
                'status' => 'active',
                'nonexistent_column' => 'value', // Should be ignored
            ],
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSortIgnoresNonSortableColumns(): void {
        $database = $this->createMockDatabase();

        // Expect only sortable columns in ORDER BY clause
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name DESC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        // Try to sort by a non-sortable column
        $request = $this->createMockRequest([
            'sort' => 'nonexistent_column:asc,name:desc',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSearchWithMultipleWords(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to be called with multi-word search patterns
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([
                    'search' => '%hello%world%test%',
                    'searchReversed' => '%test%world%hello%',
                ])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        // Add multi-word search
        $request = $this->createMockRequest([
            'search' => 'hello world test',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSortWithDefaultDirection(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to be called with default ASC direction
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name ASC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        // Add sort without explicit direction (should default to ASC)
        $request = $this->createMockRequest([
            'sort' => 'name',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSortHandlesCaseInsensitiveDirection(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to handle case-insensitive direction (DESC)
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name DESC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        // Add sort with uppercase DESC direction
        $request = $this->createMockRequest([
            'sort' => 'name:DESC',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSortHandlesWhitespaceInDirective(): void {
        $database = $this->createMockDatabase();

        // Expect the select method to handle whitespace around colons
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name DESC
LIMIT 10 OFFSET 0;"),
                $this->equalTo([])
            )
            ->willReturn([]);

        TestEntity::setDatabase($database);

        // Add sort with spaces around colon
        $request = $this->createMockRequest([
            'sort' => 'name : desc',
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testFilterableAddFiltersToQuery(): void {
        $query = $this->createMock(QueryBuilder::class);

        $filters = [
            "status" => "active",
            "category" => "test",
        ];

        // Expect where to be called twice (once for each filter)
        $query->expects($this->exactly(2))
            ->method('where')
            ->willReturnSelf();

        TestEntity::addFiltersToQuery($query, $filters);
    }

    public function testFilterableIgnoresNonFilterableColumns(): void {
        $query = $this->createMock(QueryBuilder::class);

        $filters = [
            "status" => "active",
            "nonexistent_column" => "value", // Should be ignored
        ];

        // Expect where to be called only once (for status)
        $query->expects($this->once())
            ->method('where')
            ->with("status", "=", "active")
            ->willReturnSelf();

        TestEntity::addFiltersToQuery($query, $filters);
    }

    public function testSortableAddSortToQueryWithAscending(): void {
        $query = $this->createMock(QueryBuilder::class);

        $query->expects($this->once())
            ->method('orderBy')
            ->with("name", true); // true = ascending

        TestEntity::addSortToQuery($query, ["name:asc"]);
    }

    public function testSortableAddSortToQueryWithDescending(): void {
        $query = $this->createMock(QueryBuilder::class);

        $query->expects($this->once())
            ->method('orderBy')
            ->with("created_at", false); // false = descending

        TestEntity::addSortToQuery($query, ["created_at:desc"]);
    }

    public function testSortableAddSortToQueryDefaultsToAscending(): void {
        $query = $this->createMock(QueryBuilder::class);

        $query->expects($this->once())
            ->method('orderBy')
            ->with("name", true); // true = ascending (default)

        TestEntity::addSortToQuery($query, ["name"]); // No direction specified
    }

    public function testSortableAddSortToQueryWithMultipleColumns(): void {
        $query = $this->createMock(QueryBuilder::class);

        // Expect orderBy to be called multiple times
        $query->expects($this->exactly(3))
            ->method('orderBy')
            ->willReturnSelf();

        TestEntity::addSortToQuery($query, ["name:asc", "created_at:desc", "status"]);
    }

    public function testSortableIgnoresNonSortableColumns(): void {
        $query = $this->createMock(QueryBuilder::class);

        // Should not call orderBy for non-sortable column
        $query->expects($this->never())
            ->method('orderBy');

        TestEntity::addSortToQuery($query, ["nonexistent_column:asc"]);
    }

    public function testSortableHandlesCaseInsensitiveDirection(): void {
        $query = $this->createMock(QueryBuilder::class);

        $query->expects($this->once())
            ->method('orderBy')
            ->with("name", false); // DESC

        TestEntity::addSortToQuery($query, ["name:DESC"]);
    }

    public function testSortableHandlesWhitespaceInDirective(): void {
        $query = $this->createMock(QueryBuilder::class);

        $query->expects($this->once())
            ->method('orderBy')
            ->with("name", false); // DESC

        TestEntity::addSortToQuery($query, ["name : desc"]); // Spaces around colon
    }
}
