<?php

declare(strict_types=1);

namespace JPI\CRUD\API\Tests;

use JPI\CRUD\API\Tests\Fixtures\TestEntity;
use JPI\Database;
use JPI\ORM\Entity\QueryBuilder;
use PHPUnit\Framework\TestCase;

/**
 * Test SQL queries generated by the query builder for index operations
 * 
 * Tests verify that filtering, searching, sorting, and pagination
 * produce the correct SQL queries as requested in the issue.
 */
class QueryBuilderSQLTest extends TestCase {

    private function createMockDatabase(): Database {
        return $this->createMock(Database::class);
    }

    private function createQueryBuilder(?Database $database = null): QueryBuilder {
        $entity = new TestEntity();
        return new QueryBuilder($database ?: $this->createMockDatabase(), $entity);
    }

    public function testFilteringGeneratesCorrectWhereClause(): void {
        $database = $this->createMockDatabase();
        
        // Expect the selectAll method to be called with specific SQL
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category
ORDER BY id ASC;"),
                $this->equalTo([
                    'status' => 'active',
                    'category' => 'test',
                ])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add filter for status = active
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
            'category' => 'test',
        ]);
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testSearchingGeneratesCorrectWhereClause(): void {
        $database = $this->createMockDatabase();
        
        // Expect the select method to be called with specific SQL including OR conditions
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC;"),
                $this->equalTo([
                    'search' => '%hello%world%',
                    'searchReversed' => '%world%hello%',
                ])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add search query
        TestEntity::addSearchToQuery($query, 'hello world');
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testSortingGeneratesCorrectOrderBy(): void {
        $database = $this->createMockDatabase();
        
        // Expect the select method to be called with specific ORDER BY
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name ASC, created_at DESC;"),
                $this->equalTo([])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add sorting
        TestEntity::addSortToQuery($query, ['name:asc', 'created_at:desc']);
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testMultipleFiltersWithSearch(): void {
        $database = $this->createMockDatabase();
        
        // Expect the select method to be called with combined WHERE conditions
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC;"),
                $this->equalTo([
                    'status' => 'active',
                    'search' => '%test%',
                    'searchReversed' => '%test%',
                ])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add filters
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
        ]);
        
        // Add search
        TestEntity::addSearchToQuery($query, 'test');
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testComplexQueryWithFilterSearchAndSort(): void {
        $database = $this->createMockDatabase();
        
        // Expect the select method to be called with all query modifications
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY name DESC, created_at ASC
LIMIT 10 OFFSET 10;"),
                $this->equalTo([
                    'status' => 'active',
                    'category' => 'test',
                    'search' => '%hello%world%',
                    'searchReversed' => '%world%hello%',
                ])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add all query modifications
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
            'category' => 'test',
        ]);
        
        TestEntity::addSearchToQuery($query, 'hello world');
        
        TestEntity::addSortToQuery($query, ['name:desc', 'created_at:asc']);
        
        // Add pagination
        $query->limit(10, 2); // 10 items, page 2
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testFilterIgnoresNonFilterableColumns(): void {
        $database = $this->createMockDatabase();
        
        // Expect only filterable columns in WHERE clause
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status
ORDER BY id ASC;"),
                $this->equalTo([
                    'status' => 'active',
                ])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Try to filter by a non-filterable column
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
            'nonexistent_column' => 'value',
        ]);
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testSortIgnoresNonSortableColumns(): void {
        $database = $this->createMockDatabase();
        
        // Expect only sortable columns in ORDER BY clause
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name DESC;"),
                $this->equalTo([])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Try to sort by a non-sortable column
        TestEntity::addSortToQuery($query, ['nonexistent_column:asc', 'name:desc']);
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testSearchWithMultipleWords(): void {
        $database = $this->createMockDatabase();
        
        // Expect the select method to be called with multi-word search patterns
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC;"),
                $this->equalTo([
                    'search' => '%hello%world%test%',
                    'searchReversed' => '%test%world%hello%',
                ])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add multi-word search
        TestEntity::addSearchToQuery($query, 'hello world test');
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }

    public function testSortWithDefaultDirection(): void {
        $database = $this->createMockDatabase();
        
        // Expect the select method to be called with default ASC direction
        $database->expects($this->once())
            ->method('selectAll')
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name ASC;"),
                $this->equalTo([])
            )
            ->willReturn([]);
        
        $query = $this->createQueryBuilder($database);
        
        // Add sort without explicit direction (should default to ASC)
        TestEntity::addSortToQuery($query, ['name']);
        
        // Execute the query to trigger SQL generation
        $query->select(false);
    }
}
