<?php

declare(strict_types=1);

namespace JPI\CRUD\API\Tests;

use JPI\CRUD\API\Tests\Fixtures\TestEntity;
use JPI\Database;
use JPI\ORM\Entity\QueryBuilder;
use PHPUnit\Framework\TestCase;

/**
 * Test SQL queries generated by the query builder for index operations
 * 
 * Tests verify that filtering, searching, sorting, and pagination
 * produce the correct SQL queries as requested in the issue.
 */
class QueryBuilderSQLTest extends TestCase {

    private function createMockDatabase(): Database {
        return $this->createMock(Database::class);
    }

    private function createQueryBuilder(): QueryBuilder {
        $entity = new TestEntity();
        return new QueryBuilder($this->createMockDatabase(), $entity);
    }

    /**
     * Helper method to get WHERE clause SQL from query builder
     */
    private function getWhereClause(QueryBuilder $query): string {
        $reflection = new \ReflectionClass($query);
        $whereProperty = $reflection->getProperty('where');
        $whereProperty->setAccessible(true);
        return (string)$whereProperty->getValue($query);
    }

    /**
     * Helper method to get ORDER BY clause SQL from query builder
     */
    private function getOrderByClause(QueryBuilder $query): string {
        $reflection = new \ReflectionClass($query);
        $orderByProperty = $reflection->getProperty('orderBy');
        $orderByProperty->setAccessible(true);
        return (string)$orderByProperty->getValue($query);
    }

    /**
     * Helper method to get LIMIT value from query builder
     */
    private function getLimitValue(QueryBuilder $query): ?int {
        $reflection = new \ReflectionClass($query);
        $limitProperty = $reflection->getProperty('limit');
        $limitProperty->setAccessible(true);
        return $limitProperty->getValue($query);
    }

    public function testFilteringGeneratesCorrectWhereClause(): void {
        $query = $this->createQueryBuilder();
        
        // Add filter for status = active
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
            'category' => 'test',
        ]);
        
        // Get WHERE clause SQL
        $whereSQL = $this->getWhereClause($query);
        
        // Should contain both status and category
        $this->assertStringContainsString('status', $whereSQL);
        $this->assertStringContainsString('category', $whereSQL);
        
        // Check params
        $params = $query->getParams();
        $this->assertArrayHasKey('status', $params);
        $this->assertEquals('active', $params['status']);
        $this->assertArrayHasKey('category', $params);
        $this->assertEquals('test', $params['category']);
    }

    public function testSearchingGeneratesCorrectWhereClause(): void {
        $query = $this->createQueryBuilder();
        
        // Add search query
        TestEntity::addSearchToQuery($query, 'hello world');
        
        // Get params to verify search patterns
        $params = $query->getParams();
        
        $this->assertArrayHasKey('search', $params);
        $this->assertArrayHasKey('searchReversed', $params);
        $this->assertEquals('%hello%world%', $params['search']);
        $this->assertEquals('%world%hello%', $params['searchReversed']);
        
        // Get WHERE clause SQL
        $whereSQL = $this->getWhereClause($query);
        
        // Should contain LIKE conditions for searchable columns
        $this->assertStringContainsString('LIKE', $whereSQL);
        $this->assertStringContainsString(':search', $whereSQL);
    }

    public function testSortingGeneratesCorrectOrderBy(): void {
        $query = $this->createQueryBuilder();
        
        // Add sorting
        TestEntity::addSortToQuery($query, ['name:asc', 'created_at:desc']);
        
        // Get ORDER BY clause SQL
        $orderBySQL = $this->getOrderByClause($query);
        
        // Should contain both columns with correct directions
        $this->assertStringContainsString('name', $orderBySQL);
        $this->assertStringContainsString('created_at', $orderBySQL);
        $this->assertStringContainsString('ASC', $orderBySQL);
        $this->assertStringContainsString('DESC', $orderBySQL);
    }

    public function testMultipleFiltersWithSearch(): void {
        $query = $this->createQueryBuilder();
        
        // Add filters
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
        ]);
        
        // Add search
        TestEntity::addSearchToQuery($query, 'test');
        
        // Get WHERE clause SQL
        $whereSQL = $this->getWhereClause($query);
        
        // Should have both filter and search conditions
        $this->assertStringContainsString('status', $whereSQL);
        $this->assertStringContainsString('LIKE', $whereSQL);
        
        // Check params
        $params = $query->getParams();
        $this->assertArrayHasKey('status', $params);
        $this->assertArrayHasKey('search', $params);
    }

    public function testComplexQueryWithFilterSearchAndSort(): void {
        $query = $this->createQueryBuilder();
        
        // Add all query modifications
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
            'category' => 'test',
        ]);
        
        TestEntity::addSearchToQuery($query, 'hello world');
        
        TestEntity::addSortToQuery($query, ['name:desc', 'created_at:asc']);
        
        // Add pagination
        $query->limit(10, 2); // 10 items, page 2
        
        // Verify WHERE clause contains both filters and search
        $whereSQL = $this->getWhereClause($query);
        $this->assertStringContainsString('status', $whereSQL);
        $this->assertStringContainsString('category', $whereSQL);
        $this->assertStringContainsString('LIKE', $whereSQL);
        
        // Verify ORDER BY contains both columns
        $orderBySQL = $this->getOrderByClause($query);
        $this->assertStringContainsString('name', $orderBySQL);
        $this->assertStringContainsString('created_at', $orderBySQL);
        
        // Verify LIMIT
        $this->assertEquals(10, $this->getLimitValue($query));
    }

    public function testFilterIgnoresNonFilterableColumns(): void {
        $query = $this->createQueryBuilder();
        
        // Try to filter by a non-filterable column
        TestEntity::addFiltersToQuery($query, [
            'status' => 'active',
            'nonexistent_column' => 'value',
        ]);
        
        // Get WHERE clause SQL
        $whereSQL = $this->getWhereClause($query);
        
        // Should only contain status
        $this->assertStringContainsString('status', $whereSQL);
        $this->assertStringNotContainsString('nonexistent_column', $whereSQL);
        
        // Verify only status is in params
        $params = $query->getParams();
        $this->assertArrayHasKey('status', $params);
        $this->assertArrayNotHasKey('nonexistent_column', $params);
    }

    public function testSortIgnoresNonSortableColumns(): void {
        $query = $this->createQueryBuilder();
        
        // Try to sort by a non-sortable column
        TestEntity::addSortToQuery($query, ['nonexistent_column:asc', 'name:desc']);
        
        // Get ORDER BY clause SQL
        $orderBySQL = $this->getOrderByClause($query);
        
        // Should only contain name
        $this->assertStringContainsString('name', $orderBySQL);
        $this->assertStringNotContainsString('nonexistent_column', $orderBySQL);
    }

    public function testSearchWithMultipleWords(): void {
        $query = $this->createQueryBuilder();
        
        // Add multi-word search
        TestEntity::addSearchToQuery($query, 'hello world test');
        
        // Check params
        $params = $query->getParams();
        
        // Should have wildcards between words
        $this->assertEquals('%hello%world%test%', $params['search']);
        $this->assertEquals('%test%world%hello%', $params['searchReversed']);
        
        // Get WHERE clause SQL
        $whereSQL = $this->getWhereClause($query);
        
        // Should have OR conditions for searchable columns
        $this->assertStringContainsString('OR', $whereSQL);
        $this->assertStringContainsString('name', $whereSQL);
        $this->assertStringContainsString('description', $whereSQL);
    }

    public function testSortWithDefaultDirection(): void {
        $query = $this->createQueryBuilder();
        
        // Add sort without explicit direction (should default to ASC)
        TestEntity::addSortToQuery($query, ['name']);
        
        // Get ORDER BY clause SQL
        $orderBySQL = $this->getOrderByClause($query);
        
        // Should contain name with ASC (default)
        $this->assertStringContainsString('name', $orderBySQL);
        $this->assertStringContainsString('ASC', $orderBySQL);
    }
}
