<?php

declare(strict_types=1);

namespace JPI\CRUD\API\Tests\Unit;

use JPI\CRUD\API\Tests\Fixtures\TestCrudService;
use JPI\CRUD\API\Tests\Fixtures\TestEntity;
use JPI\CRUD\API\Tests\Fixtures\TestRelatedEntity;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * Test SQL queries generated by CrudService index operations
 *
 * Tests verify that filtering, searching, sorting, and pagination
 * produce the correct SQL queries as requested in the issue.
 *
 * @covers \JPI\CRUD\API\CrudService::index
 * @covers \JPI\CRUD\API\Entity\FilterableTrait
 * @covers \JPI\CRUD\API\Entity\SearchableTrait
 * @covers \JPI\CRUD\API\Entity\SortableTrait
 */
final class CrudServiceIndexTest extends AbstractCrudServiceTestCase {

    public function testLimit(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 3;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest(queryParams: [
            "limit" => 3,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testPagination(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10 OFFSET 20;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $database->expects($this->once())
            ->method("selectFirst")
            ->willReturn(["count" => 20])
        ;

        $request = $this->createRequest(queryParams: [
            "page" => 3,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testFiltering(): void {
        $this->createDatabase()
            ->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([
                    "status" => "active",
                    "category" => "test",
                ])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest(queryParams: [
            "filters" => [
                "status" => "active",
                "category" => "test",
                "nonexistent_column" => "foo",
            ],
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSearching(): void {
        $this->createDatabase()
            ->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([
                    "search" => "%hello%world%",
                    "searchReversed" => "%world%hello%",
                ])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest(queryParams: [
            "search" => "hello world",
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testSorting(): void {
        $this->createDatabase()
            ->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY name ASC, created_at DESC, id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest(queryParams: [
            "sort" => "name:asc,nonexistent_column,created_at : DESC,id", // Nonexistent, space and case variations
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testFiltersWithSearch(): void {
        $this->createDatabase()
            ->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([
                    "status" => "active",
                    "search" => "%test%",
                    "searchReversed" => "%test%",
                ])
            )
            ->willReturn([])
        ;

        $request = $this->createRequest(queryParams: [
            "filters" => [
                "status" => "active",
            ],
            "search" => "test",
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public function testEverything(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
WHERE status = :status AND category = :category AND (name LIKE :search OR name LIKE :searchReversed OR description LIKE :search OR description LIKE :searchReversed)
ORDER BY name DESC, created_at ASC
LIMIT 10 OFFSET 10;"),
                $this->equalTo([
                    "status" => "active",
                    "category" => "test",
                    "search" => "%hello%world%",
                    "searchReversed" => "%world%hello%",
                ])
            )
            ->willReturn([])
        ;

        $database->expects($this->once())
            ->method("selectFirst")
            ->willReturn(["count" => 20])
        ;

        $request = $this->createRequest(queryParams: [
            "filters" => [
                "status" => "active",
                "category" => "test",
            ],
            "search" => "hello world",
            "sort" => "name:desc,created_at:asc",
            "limit" => 10,
            "page" => 2,
        ]);

        $service = new TestCrudService(TestEntity::class);
        $service->index($request);
    }

    public static function invalidValueProvider(): array {
        return [
            "limit: string value (non-numeric)" => [["limit" => "not a number"]],
            "limit: array value" => [["limit" => ["2"]]],
            "limit: negative number" => [["limit" => -5]],
            "limit: zero" => [["limit" => 0]],
            "page: string value (non-numeric)" => [["page" => "not a number"]],
            "page: array value" => [["page" => ["2"]]],
            "page: negative number" => [["page" => -2]],
            "page: zero" => [["page" => 0]],
            "filters: string value instead of array" => [["filters" => "im a string filter"]],
            "filters: nested array values" => [["filters" => ["key" => ["im nested"]]]],
            "search: array value instead of string" => [["search" => ["in array"]]],
            "sort: array value instead of string" => [["sort" => ["in array"]]],
        ];
    }

    #[DataProvider('invalidValueProvider')]
    public function testInvalidValue(array $queryParams): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->equalTo("SELECT *
FROM test_entities
ORDER BY id ASC
LIMIT 10;"),
                $this->equalTo([])
            )
            ->willReturn([])
        ;

        $service = new TestCrudService(TestEntity::class);
        $service->index($this->createRequest(queryParams: $queryParams));
    }

    public function testWithBelongsTo(): void {
        $this->createDatabase()
            ->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->stringContains("SELECT *
FROM test_entities"),
                $this->anything()
            )
            ->willReturn([
                [
                    "id" => 1,
                    "name" => "Entity 1",
                    "description" => null,
                    "status" => null,
                    "category" => null,
                    "age" => null,
                    "created_at" => null,
                    "related_id" => 10,
                ],
                [
                    "id" => 2,
                    "name" => "Entity 2",
                    "description" => null,
                    "status" => null,
                    "category" => null,
                    "age" => null,
                    "created_at" => null,
                    "related_id" => 11,
                ],
            ])
        ;

        $this->createDatabase(TestRelatedEntity::class)
            ->expects($this->once())
            ->method("selectAll")
            ->willReturn(
                [
                    ["id" => 10, "name" => "Related 1", "description" => null],
                    ["id" => 11, "name" => "Related 2", "description" => null],
                ]
            )
        ;

        $request = $this->createRequest(queryParams: ["include" => "related"]);

        $service = new TestCrudService(TestEntity::class);
        $entities = $service->index($request);

        $this->assertCount(2, $entities);

        // Verify relationships are loaded
        $this->assertTrue(isset($entities[0]->related));
        $this->assertSame(10, $entities[0]->related->getId());
        $this->assertSame("Related 1", $entities[0]->related->name);

        $this->assertTrue(isset($entities[1]->related));
        $this->assertSame(11, $entities[1]->related->getId());
        $this->assertSame("Related 2", $entities[1]->related->name);
    }

    public function testWithHasOne(): void {
        $this->createDatabase()
            ->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->stringContains("SELECT *
FROM test_entities"),
                $this->anything()
            )
            ->willReturn([
                [
                    "id" => 1,
                    "name" => "Parent 1",
                    "description" => null,
                    "status" => null,
                    "category" => null,
                    "age" => null,
                    "created_at" => null,
                ],
                [
                    "id" => 2,
                    "name" => "Parent 2",
                    "description" => null,
                    "status" => null,
                    "category" => null,
                    "age" => null,
                    "created_at" => null,
                ],
            ])
        ;

        $this->createDatabase(TestRelatedEntity::class)
            ->expects($this->once())
            ->method("selectAll")
            ->willReturn(
                [
                    ["id" => 20, "name" => "Child 1", "description" => null, "parent_id" => 1],
                    ["id" => 21, "name" => "Child 2", "description" => null, "parent_id" => 2],
                ]
            )
        ;

        $request = $this->createRequest(queryParams: ["include" => "child"]);

        $service = new TestCrudService(TestEntity::class);
        $entities = $service->index($request);

        $this->assertCount(2, $entities);

        // Verify relationships are loaded
        $this->assertTrue(isset($entities[0]->child));
        $this->assertSame(20, $entities[0]->child->getId());
        $this->assertSame("Child 1", $entities[0]->child->name);

        $this->assertTrue(isset($entities[1]->child));
        $this->assertSame(21, $entities[1]->child->getId());
        $this->assertSame("Child 2", $entities[1]->child->name);
    }

    public function testWithHasMany(): void {
        $database = $this->createDatabase();

        $database->expects($this->once())
            ->method("selectAll")
            ->with(
                $this->stringContains("SELECT *
FROM test_entities"),
                $this->anything()
            )
            ->willReturn([
                [
                    "id" => 1,
                    "name" => "Parent 1",
                    "description" => null,
                    "status" => null,
                    "category" => null,
                    "age" => null,
                    "created_at" => null,
                ],
                [
                    "id" => 2,
                    "name" => "Parent 2",
                    "description" => null,
                    "status" => null,
                    "category" => null,
                    "age" => null,
                    "created_at" => null,
                ],
            ])
        ;

        $this->createDatabase(TestRelatedEntity::class)
            ->expects($this->once())
            ->method("selectAll")
            ->willReturn(
                [
                    ["id" => 30, "name" => "Child 1a", "description" => null, "parent_id" => 1],
                    ["id" => 31, "name" => "Child 1b", "description" => null, "parent_id" => 1],
                    ["id" => 32, "name" => "Child 2a", "description" => null, "parent_id" => 2],
                ],
            )
        ;

        $request = $this->createRequest(queryParams: ["include" => "children"]);

        $service = new TestCrudService(TestEntity::class);
        $entities = $service->index($request);

        $this->assertCount(2, $entities);

        // Verify relationships are loaded
        $this->assertTrue(isset($entities[0]->children));
        $this->assertCount(2, $entities[0]->children);
        $this->assertSame(30, $entities[0]->children[0]->getId());
        $this->assertSame("Child 1a", $entities[0]->children[0]->name);
        $this->assertSame(31, $entities[0]->children[1]->getId());
        $this->assertSame("Child 1b", $entities[0]->children[1]->name);

        $this->assertTrue(isset($entities[1]->children));
        $this->assertCount(1, $entities[1]->children);
        $this->assertSame(32, $entities[1]->children[0]->getId());
        $this->assertSame("Child 2a", $entities[1]->children[0]->name);
    }
}
